"""rename_field_name

Revision ID: 45a0b4ceab02
Revises: 213b85fb1ed1
Create Date: 2026-06-26 21:50:46.894577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a0b4ceab02'
down_revision: Union[str, Sequence[str], None] = '213b85fb1ed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('full_path', sa.String(length=1024), nullable=False))
    op.drop_column('files', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.drop_column('files', 'full_path')
    # ### end Alembic commands ###
